version: "3.7"
services:
  api:
    container_name: api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"  
    environment:
    - REDIS_HOST=local:redis
    - REDIS_PORT=6379
    - REDIS_TIMEOUT=6000
    - REDIS_SSL=false
    - REDIS_DB=0
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "/redis.conf", "--port", "6379"]
    volumes:
      - type: volume
        source: redis-data
        target: /redis.conf
        
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "3001:8081"
volumes:
  redis-data:
